name: Lab2 Workflow

on:
  workflow_dispatch:
    inputs:
      run-job:
        description: Run Specific Job
        required: false
        default: false
        type: boolean
      message:
        description: Message
        required: true
        type: string

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing run-job boolean value
        if: ${{ inputs.run-job }}
        run: echo "Run Job Value: ${{ inputs.run-job }}"

