name: Lab Workflow

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        required: false
        type: boolean
      custom_message:
        description: 'Enter a custom message'
        required: true
        type: string

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ github.event.inputs.custom_message }}"

